import { initializeApp, deleteApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAnalytics } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-analytics.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut, createUserWithEmailAndPassword } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, deleteDoc, onSnapshot, query, orderBy, serverTimestamp, writeBatch } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const firebaseConfig = {
  apiKey: "AIzaSyBfiPTfmUFpKPCNN5YGE65UbnyYqg-X8IU",
  authDomain: "heritage2-a311b.firebaseapp.com",
  projectId: "heritage2-a311b",
  storageBucket: "heritage2-a311b.firebasestorage.app",
  messagingSenderId: "1061852868611",
  appId: "1:1061852868611:web:8117d3e3fe0c92da169e36",
  measurementId: "G-NDYPDMN692"
};

const firebaseApp=initializeApp(firebaseConfig);
try{ getAnalytics(firebaseApp); }catch(e){}
const auth=getAuth(firebaseApp), db=getFirestore(firebaseApp);
const C={users:'heritage_users',projects:'heritage_projects',blocks:'heritage_blocks',customers:'heritage_customers',sales:'heritage_sales',payments:'heritage_payments',documents:'heritage_documents',settings:'heritage_settings',audit:'heritage_audit_logs'};
const state={user:null,profile:null,projects:[],blocks:[],customers:[],sales:[],payments:[],documents:[],users:[],settings:{companyName:'HERITAGE ASIA HOLDINGS (PVT) LTD',companyEmail:'',emailServiceId:'',emailTemplateId:'',emailPublicKey:''},unsubs:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));
const money=n=>`LKR ${Number(n||0).toLocaleString('en-LK',{maximumFractionDigits:0})}`;
const id=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const today=()=>new Date().toISOString().slice(0,10);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.add('hidden'),3200)}
function role(){return state.profile?.role||''} function isAdmin(){return role()==='admin'} function isManager(){return ['admin','director','manager'].includes(role())} function isSales(){return ['admin','director','manager','sales_officer','site_officer'].includes(role())} function isFinance(){return ['admin','director','manager','accountant'].includes(role())}
function audit(action,entityType,entityId,details={}){if(!state.user)return; addDoc(collection(db,C.audit),{action,entityType,entityId,details,userId:state.user.uid,userName:state.profile?.name||state.user.email,createdAt:Date.now()}).catch(()=>{})}
function setCloud(ok,text){$('#cloudDot').className=`cloud-dot ${ok===true?'ready':ok===false?'error':''}`;$('#cloudText').textContent=text}

function showLogin(msg=''){ $('#authGate').classList.remove('hidden'); $('#appShell').classList.add('hidden'); $('#bootstrapPanel').classList.add('hidden'); if(msg){$('#authMsg').textContent=msg;$('#authMsg').classList.remove('hidden')} }
function showBootstrap(){ $('#authGate').classList.remove('hidden'); $('#appShell').classList.add('hidden'); $('#bootstrapPanel').classList.remove('hidden'); $('#authMsg').classList.add('hidden') }
function showApp(){ $('#authGate').classList.add('hidden'); $('#appShell').classList.remove('hidden'); $('#userName').textContent=state.profile?.name||state.user?.email||'User'; $('#userRole').textContent=(role()||'user').replaceAll('_',' '); $$('.admin-only').forEach(x=>x.classList.toggle('hidden',!isAdmin())); $$('.manager-action').forEach(x=>x.classList.toggle('hidden',!isManager())); $$('.sales-action').forEach(x=>x.classList.toggle('hidden',!isSales())); lucide.createIcons(); }

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{$('#authMsg').classList.add('hidden');await signInWithEmailAndPassword(auth,$('#loginEmail').value.trim(),$('#loginPassword').value)}catch(err){showLogin('Login failed. Check Firebase Authentication email/password and try again.')}});
$('#signOutBtn').addEventListener('click',()=>signOut(auth));
$('#bootstrapBtn').addEventListener('click',async()=>{if(!state.user)return;const name=$('#bootstrapName').value.trim()||'Administrator';try{await setDoc(doc(db,C.users,state.user.uid),{uid:state.user.uid,email:state.user.email,name,role:'admin',active:true,createdAt:Date.now(),updatedAt:Date.now()});toast('Admin profile created. Publish secure Firestore rules now.')}catch(e){toast('Bootstrap blocked. Temporarily publish the FIRST_ADMIN rules file.')}});

onAuthStateChanged(auth,async user=>{state.user=user;state.profile=null;state.unsubs.forEach(u=>u());state.unsubs=[];if(!user){showLogin();return}setCloud(null,'Connecting...');try{const snap=await getDoc(doc(db,C.users,user.uid));if(!snap.exists()){showBootstrap();return}state.profile={id:snap.id,...snap.data()};if(state.profile.active===false){await signOut(auth);showLogin('This account is disabled.');return}showApp();startRealtime();}catch(e){setCloud(false,'Rules blocked');showLogin('Could not load user profile. Check Firestore rules.')}});

function startRealtime(){
  const listen=(key,col,cb)=>state.unsubs.push(onSnapshot(collection(db,col),snap=>{state[key]=snap.docs.map(d=>({id:d.id,...d.data()}));cb?.();setCloud(true,'Live Firestore')},e=>setCloud(false,'Sync error')));
  listen('projects',C.projects,renderAll);listen('blocks',C.blocks,renderAll);listen('customers',C.customers,renderAll);listen('sales',C.sales,renderAll);listen('payments',C.payments,renderAll);listen('documents',C.documents,renderAll);listen('users',C.users,renderAll);
  state.unsubs.push(onSnapshot(doc(db,C.settings,'company'),snap=>{if(snap.exists())state.settings={...state.settings,...snap.data()};renderSettings()},()=>{}));
}
function renderAll(){renderDashboard();renderProjects();renderBlockFilters();renderBlocks();renderSales();renderCustomers();renderPayments();renderDocuments();renderUsers();lucide.createIcons()}

const titles={dashboard:'Dashboard',projects:'Land Projects',blocks:'Block Inventory',sales:'Sales / Reservations',customers:'Customers',payments:'Payments',documents:'Documents',users:'Users',settings:'Settings'};
function setView(v){$$('.app-view').forEach(x=>x.classList.add('hidden'));$(`#view-${v}`)?.classList.remove('hidden');$('#pageTitle').textContent=titles[v]||v;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));lucide.createIcons()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));

function renderDashboard(){
 const available=state.blocks.filter(b=>b.status==='AVAILABLE').length,reserved=state.blocks.filter(b=>b.status==='RESERVED').length,sold=state.blocks.filter(b=>b.status==='SOLD').length;
 const income=state.payments.reduce((s,p)=>s+Number(p.amount||0),0),outstanding=state.sales.reduce((s,x)=>s+Math.max(0,Number(x.totalPrice||0)-Number(x.paidTotal||0)),0);
 $('#statsGrid').innerHTML=[['Projects',state.projects.length],['Available Blocks',available],['Sold / Reserved',sold+reserved],['Collected',money(income)]].map(([a,b],i)=>`<div class="stat-card"><small>${a}</small><strong class="${i===3?'accent':''}">${b}</strong></div>`).join('');
 const recent=[...state.sales].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,6); $('#recentSales').innerHTML=recent.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Project / Block</th><th>Status</th><th>Total</th></tr></thead><tbody>${recent.map(s=>`<tr><td>${esc(s.customerName)}</td><td>${esc(s.projectName)} / ${esc(s.blockNo)}</td><td><span class="pill ${String(s.status).toLowerCase()}">${esc(s.status)}</span></td><td>${money(s.totalPrice)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No sales yet.</div>';
 $('#blockStatusSummary').innerHTML=`<div class="grid grid-cols-2 gap-3"><div class="stat-card"><small>Available</small><strong>${available}</strong></div><div class="stat-card"><small>Reserved</small><strong>${reserved}</strong></div><div class="stat-card"><small>Sold</small><strong>${sold}</strong></div><div class="stat-card"><small>Outstanding</small><strong class="accent text-lg">${money(outstanding)}</strong></div></div>`;
}

function renderProjects(){
 $('#projectsGrid').innerHTML=state.projects.length?state.projects.map(p=>{const bs=state.blocks.filter(b=>b.projectId===p.id);return`<article class="project-card"><div class="project-image">${p.imageData?`<img src="${p.imageData}" alt="">`:`<i data-lucide="map-pinned" class="text-amber-300"></i>`}</div><div class="project-body"><p class="eyebrow">LAND PROJECT</p><h3 class="text-xl font-black mt-1">${esc(p.name)}</h3><p class="text-xs text-zinc-500 mt-1">${esc(p.location||'')}</p><div class="grid grid-cols-3 gap-2 mt-4 text-center"><div><b>${bs.length}</b><small class="block text-zinc-500">Blocks</small></div><div><b>${bs.filter(x=>x.status==='AVAILABLE').length}</b><small class="block text-zinc-500">Available</small></div><div><b>${bs.filter(x=>x.status==='SOLD').length}</b><small class="block text-zinc-500">Sold</small></div></div>${isManager()?`<div class="flex gap-2 mt-4"><button class="btn btn-dark text-xs" onclick="window.editProject('${p.id}')">Edit</button><button class="btn btn-dark text-xs" onclick="window.addBlockFor('${p.id}')">Add Block</button></div>`:''}</div></article>`}).join(''):'<div class="empty md:col-span-2 xl:col-span-3">No land projects yet.</div>';
}
function renderBlockFilters(){const cur=$('#blockProjectFilter').value;$('#blockProjectFilter').innerHTML='<option value="">All Projects</option>'+state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#blockProjectFilter').value=cur}
function renderBlocks(){const pid=$('#blockProjectFilter').value,st=$('#blockStatusFilter').value;const list=state.blocks.filter(b=>(!pid||b.projectId===pid)&&(!st||b.status===st));$('#blocksGrid').innerHTML=list.length?list.map(b=>`<button class="block-card" onclick="window.blockAction('${b.id}')"><span class="pill ${String(b.status).toLowerCase()}">${esc(b.status)}</span><h4 class="mt-3">Block ${esc(b.blockNo)}</h4><p>${esc(b.projectName||'')}</p><p>${esc(b.perches||0)} perches</p><div class="price">${money(b.totalPrice||Number(b.perches||0)*Number(b.pricePerPerch||0))}</div></button>`).join(''):'<div class="empty">No blocks match this filter.</div>'}
$('#blockProjectFilter').addEventListener('change',renderBlocks);$('#blockStatusFilter').addEventListener('change',renderBlocks);

function renderSales(){const list=[...state.sales].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('#salesTable').innerHTML=list.length?table(['Customer','Project / Block','Type','Total','Paid','Balance','Status',''],list.map(s=>[esc(s.customerName),`${esc(s.projectName)} / ${esc(s.blockNo)}`,esc(s.saleType),money(s.totalPrice),money(s.paidTotal),money(Math.max(0,s.totalPrice-s.paidTotal)),`<span class="pill ${String(s.status).toLowerCase()}">${esc(s.status)}</span>`,`<button class="btn btn-dark text-xs" onclick="window.openSale('${s.id}')">Open</button>`])):'<div class="empty">No sales or reservations yet.</div>'}
function renderCustomers(){const list=[...state.customers].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('#customersTable').innerHTML=list.length?table(['Customer','NIC / Passport','Phone','Email','Address'],list.map(c=>[esc(c.name),esc(c.nic),esc(c.phone),esc(c.email),esc(c.address)])):'<div class="empty">No customers yet.</div>'}
function renderPayments(){const list=[...state.payments].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('#paymentsTable').innerHTML=list.length?table(['Receipt','Customer','Project / Block','Amount','Method','Date'],list.map(p=>[esc(p.receiptNo),esc(p.customerName),`${esc(p.projectName)} / ${esc(p.blockNo)}`,money(p.amount),esc(p.method),esc(p.paymentDate)])):'<div class="empty">No payments yet.</div>'}
function renderDocuments(){const list=[...state.documents].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('#documentsTable').innerHTML=list.length?table(['Document','Customer','Project / Block','Email','Created',''],list.map(d=>[esc(d.documentNo),esc(d.customerName),`${esc(d.projectName)} / ${esc(d.blockNo)}`,`<span class="pill ${d.emailStatus==='SENT'?'available':d.emailStatus==='FAILED'?'sold':'hold'}">${esc(d.emailStatus||'SAVED')}</span>`,new Date(d.createdAt||Date.now()).toLocaleString(),`<div class="flex gap-2 flex-wrap"><button class="btn btn-dark text-xs" onclick="window.downloadDoc('${d.id}')">PDF</button>${d.emailStatus!=='SENT'&&d.customerEmail?`<button class="btn btn-outline-gold text-xs" onclick="window.resendDocEmail('${d.id}')">Retry Email</button>`:''}</div>`])):'<div class="empty">No generated documents yet.</div>'}
function renderUsers(){if(!isAdmin())return;$('#usersTable').innerHTML=state.users.length?table(['Name','Email','Role','Status'],state.users.map(u=>[esc(u.name),esc(u.email),esc((u.role||'').replaceAll('_',' ')),u.active===false?'Disabled':'Active'])):'<div class="empty">No users.</div>'}
function renderSettings(){if(!$('#setCompanyName'))return;$('#setCompanyName').value=state.settings.companyName||'';$('#setCompanyEmail').value=state.settings.companyEmail||'';$('#setEmailService').value=state.settings.emailServiceId||'';$('#setEmailTemplate').value=state.settings.emailTemplateId||'';$('#setEmailPublicKey').value=state.settings.emailPublicKey||''}
function table(head,rows){return`<div class="table-wrap"><table class="data-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

function modal(html){$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden');lucide.createIcons()} function closeModal(){$('#modal').classList.add('hidden');$('#modalCard').innerHTML=''} window.closeModal=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function modalHead(title,sub=''){return`<div class="modal-head"><div><p class="eyebrow">HERITAGE ASIA</p><h3>${title}</h3><p class="text-sm text-zinc-500 mt-1">${sub}</p></div><button class="icon-btn" onclick="closeModal()"><i data-lucide="x"></i></button></div>`}

$('#newProjectBtn').addEventListener('click',()=>projectModal());
window.editProject=id=>projectModal(state.projects.find(x=>x.id===id));
function projectModal(p={}){modal(`${modalHead(p.id?'Edit Project':'New Land Project','Project image is compressed and stored directly in Firestore.')}<form id="projectForm" class="grid md:grid-cols-2 gap-4 mt-5"><label class="field"><span>Project Name</span><input id="pName" required value="${esc(p.name||'')}"></label><label class="field"><span>Location</span><input id="pLocation" value="${esc(p.location||'')}"></label><label class="field"><span>Default Price / Perch</span><input id="pPrice" type="number" min="0" value="${Number(p.pricePerPerch||0)}"></label><label class="field"><span>Status</span><select id="pStatus"><option>ACTIVE</option><option>UPCOMING</option><option>CLOSED</option></select></label><label class="field md:col-span-2"><span>Project Image</span><input id="pImage" type="file" accept="image/*"><img id="pPreview" class="image-preview ${p.imageData?'':'hidden'}" ${p.imageData?`src="${p.imageData}"`:''}></label><label class="field md:col-span-2"><span>Notes</span><textarea id="pNotes" rows="3">${esc(p.notes||'')}</textarea></label><div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn btn-dark" onclick="closeModal()">Cancel</button><button class="btn btn-gold"><i data-lucide="save"></i>Save Project</button></div></form>`);$('#pStatus').value=p.status||'ACTIVE';let image=p.imageData||'';$('#pImage').addEventListener('change',async e=>{if(e.target.files[0]){image=await compressImage(e.target.files[0],1000,0.55);$('#pPreview').src=image;$('#pPreview').classList.remove('hidden')}});$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();if(!isManager())return toast('No permission');const data={name:$('#pName').value.trim(),location:$('#pLocation').value.trim(),pricePerPerch:Number($('#pPrice').value||0),status:$('#pStatus').value,notes:$('#pNotes').value.trim(),imageData:image,updatedAt:Date.now()};try{if(p.id)await updateDoc(doc(db,C.projects,p.id),data);else await addDoc(collection(db,C.projects),{...data,createdAt:Date.now(),createdBy:state.user.uid});audit(p.id?'UPDATE_PROJECT':'CREATE_PROJECT','project',p.id||data.name);closeModal();toast('Project saved')}catch(err){toast('Could not save project: '+err.message)}})}

$('#newBlockBtn').addEventListener('click',()=>blockModal()); window.addBlockFor=pid=>blockModal({projectId:pid});
function blockModal(b={}){modal(`${modalHead(b.id?'Edit Block':'Add Block','Total price is calculated automatically: perches × price per perch.')}<form id="blockForm" class="grid md:grid-cols-2 gap-4 mt-5"><label class="field"><span>Project</span><select id="bProject" required><option value="">Select project</option>${state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label class="field"><span>Block No</span><input id="bNo" required value="${esc(b.blockNo||'')}"></label><label class="field"><span>Perches</span><input id="bPerches" type="number" step="0.01" min="0" inputmode="decimal" value="${Number(b.perches||0)}"></label><label class="field"><span>Price / Perch</span><input id="bPPP" type="number" step="0.01" min="0" inputmode="decimal" value="${Number(b.pricePerPerch||0)}"></label><label class="field"><span>Total Price (Auto)</span><input id="bTotal" type="number" min="0" readonly value="${Number(b.totalPrice||0)}"><small class="calc-hint" id="bCalcHint">Perches × Price / Perch</small></label><label class="field"><span>Status</span><select id="bStatus"><option>AVAILABLE</option><option>HOLD</option><option>RESERVED</option><option>SOLD</option></select></label><div class="md:col-span-2 flex justify-end"><button class="btn btn-gold">Save Block</button></div></form>`);$('#bProject').value=b.projectId||'';$('#bStatus').value=b.status||'AVAILABLE';const calc=()=>{const perches=Number($('#bPerches').value||0),ppp=Number($('#bPPP').value||0),total=Math.round((perches*ppp+Number.EPSILON)*100)/100;$('#bTotal').value=total;$('#bCalcHint').textContent=`${perches.toLocaleString('en-LK')} × ${money(ppp)} = ${money(total)}`};const applyProjectPrice=(force=false)=>{const p=state.projects.find(x=>x.id===$('#bProject').value);if(p&&(force||!Number($('#bPPP').value)))$('#bPPP').value=Number(p.pricePerPerch||0);calc()};$('#bPerches').addEventListener('input',calc);$('#bPPP').addEventListener('input',calc);$('#bProject').addEventListener('change',()=>applyProjectPrice(true));if(!b.id&&b.projectId)applyProjectPrice(true);else calc();$('#blockForm').addEventListener('submit',async e=>{e.preventDefault();if(!isManager())return toast('No permission');const p=state.projects.find(x=>x.id===$('#bProject').value);if(!p)return toast('Select a project');calc();const perches=Number($('#bPerches').value||0),ppp=Number($('#bPPP').value||0);if(perches<=0||ppp<=0)return toast('Enter valid perches and price per perch');const data={projectId:p.id,projectName:p.name,blockNo:$('#bNo').value.trim(),perches,pricePerPerch:ppp,totalPrice:Number($('#bTotal').value||0),status:$('#bStatus').value,updatedAt:Date.now()};try{if(b.id)await updateDoc(doc(db,C.blocks,b.id),data);else await addDoc(collection(db,C.blocks),{...data,createdAt:Date.now()});audit('SAVE_BLOCK','block',b.id||data.blockNo);closeModal();toast('Block saved')}catch(err){toast(err.message)}})}
window.blockAction=bid=>{const b=state.blocks.find(x=>x.id===bid);if(!b)return;if(isSales()&&b.status==='AVAILABLE')saleModal({blockId:b.id,projectId:b.projectId});else if(isManager())blockModal(b);else toast(`${b.status} block`)};

$('#newSaleBtn').addEventListener('click',()=>saleModal());$('#quickSaleBtn').addEventListener('click',()=>saleModal());
function saleModal(seed={}){if(!isSales())return toast('No permission');const avail=state.blocks.filter(b=>b.status==='AVAILABLE'||b.id===seed.blockId);modal(`${modalHead('New Sale / Reservation','Customer and officer signatures are captured on this device.')}<form id="saleForm" class="grid md:grid-cols-2 gap-4 mt-5">
<label class="field"><span>Project</span><select id="sProject" required><option value="">Select project</option>${state.projects.filter(p=>p.status!=='CLOSED').map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label>
<label class="field"><span>Available Block</span><select id="sBlock" required><option value="">Select block</option></select></label>
<label class="field"><span>Transaction Type</span><select id="sType"><option value="RESERVATION">Reservation</option><option value="SALE">Sale</option></select></label>
<label class="field"><span>Total Price (From Block)</span><input id="sPrice" type="number" min="0" readonly required><small id="sPriceBreakdown" class="calc-hint">Select a block to calculate the total.</small></label>
<label class="field"><span>Customer Full Name</span><input id="sCustomer" required></label><label class="field"><span>NIC / Passport</span><input id="sNic" required></label>
<label class="field"><span>Phone</span><input id="sPhone" type="tel" inputmode="tel" required></label><label class="field email-required"><span>Customer Email <b>• PDF Auto Delivery</b></span><input id="sEmail" type="email" autocomplete="email" placeholder="customer@example.com" required><small>The signed PDF is emailed here automatically immediately after confirmation.</small></label>
<label class="field md:col-span-2"><span>Address</span><textarea id="sAddress" rows="2"></textarea></label>
<label class="field"><span>Payment Now</span><input id="sPaid" type="number" min="0" value="0"></label><label class="field"><span>Payment Method</span><select id="sMethod"><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Cheque</option><option>Online</option></select></label>
<label class="field md:col-span-2"><span>Customer NIC / ID Photo (optional)</span><input id="sIdPhoto" type="file" accept="image/*"><img id="sIdPreview" class="image-preview hidden"></label>
<div class="md:col-span-2 grid md:grid-cols-2 gap-4"><div><p class="text-sm font-black mb-2">Customer Signature</p><div class="signature-wrap"><canvas id="customerSig"></canvas></div><div class="sig-actions"><button type="button" class="btn btn-dark text-xs" data-clear="customerSig">Clear</button></div></div><div><p class="text-sm font-black mb-2">Sales / Site Officer Signature</p><div class="signature-wrap"><canvas id="officerSig"></canvas></div><div class="sig-actions"><button type="button" class="btn btn-dark text-xs" data-clear="officerSig">Clear</button></div></div></div>
<label class="field md:col-span-2"><span>Notes / Special Terms</span><textarea id="sNotes" rows="3"></textarea></label>
<div class="md:col-span-2 notice">Confirming will reserve/sell the block, create the customer, payment receipt, signed PDF and Firestore document record. If EmailJS is configured, the PDF is emailed automatically.</div>
<div class="md:col-span-2 flex justify-end gap-2"><button type="button" class="btn btn-dark" onclick="closeModal()">Cancel</button><button id="confirmSaleBtn" class="btn btn-gold"><i data-lucide="badge-check"></i>Confirm & Generate PDF</button></div></form>`);
 const updateBlocks=()=>{const pid=$('#sProject').value;const bl=avail.filter(b=>b.projectId===pid);$('#sBlock').innerHTML='<option value="">Select block</option>'+bl.map(b=>`<option value="${b.id}">Block ${esc(b.blockNo)} — ${money(b.totalPrice)}</option>`).join('');if(seed.blockId){$('#sBlock').value=seed.blockId;$('#sBlock').dispatchEvent(new Event('change'))}};$('#sProject').value=seed.projectId||'';$('#sProject').addEventListener('change',updateBlocks);$('#sBlock').addEventListener('change',()=>{const b=state.blocks.find(x=>x.id===$('#sBlock').value);if(b){const total=Number(b.perches||0)*Number(b.pricePerPerch||0);$('#sPrice').value=Number(b.totalPrice||total);$('#sPriceBreakdown').textContent=`${Number(b.perches||0).toLocaleString('en-LK')} perches × ${money(b.pricePerPerch||0)} = ${money(b.totalPrice||total)}`;}else{$('#sPrice').value='';$('#sPriceBreakdown').textContent='Select a block to calculate the total.'}});updateBlocks();
 let idPhoto='';$('#sIdPhoto').addEventListener('change',async e=>{if(e.target.files[0]){idPhoto=await compressImage(e.target.files[0],900,.5);$('#sIdPreview').src=idPhoto;$('#sIdPreview').classList.remove('hidden')}});
 const sig1=setupSignature($('#customerSig')),sig2=setupSignature($('#officerSig'));$$('[data-clear]').forEach(b=>b.addEventListener('click',()=>{const c=$('#'+b.dataset.clear);c.getContext('2d').clearRect(0,0,c.width,c.height);c.dataset.ink='0'}));
 $('#saleForm').addEventListener('submit',async e=>{e.preventDefault();const block=state.blocks.find(x=>x.id===$('#sBlock').value),project=state.projects.find(x=>x.id===$('#sProject').value);if(!block||!project)return toast('Select a project and available block');if(block.status!=='AVAILABLE')return toast('This block is no longer available');const customerEmail=$('#sEmail').value.trim();if(!customerEmail||!$('#sEmail').checkValidity())return toast('Enter a valid customer email for automatic PDF delivery');if(!state.settings.emailServiceId||!state.settings.emailTemplateId||!state.settings.emailPublicKey)return toast('Automatic PDF email is not configured. Admin: complete EmailJS settings first.');if($('#customerSig').dataset.ink!=='1'||$('#officerSig').dataset.ink!=='1')return toast('Both signatures are required');const total=Number($('#sPrice').value||0),paid=Number($('#sPaid').value||0);if(paid>total)return toast('Payment cannot exceed total price');const customerSig=compressCanvas($('#customerSig'),620,220,.55),officerSig=compressCanvas($('#officerSig'),620,220,.55);const saleId=id('sale'),customerId=id('cust'),paymentId=paid>0?id('pay'):'';const docNo=`HAH-${$('#sType').value==='SALE'?'SAL':'RES'}-${new Date().getFullYear()}-${String(Date.now()).slice(-7)}`;const receiptNo=paid>0?`HAH-RC-${String(Date.now()).slice(-8)}`:'';const customer={name:$('#sCustomer').value.trim(),nic:$('#sNic').value.trim(),phone:$('#sPhone').value.trim(),email:$('#sEmail').value.trim(),address:$('#sAddress').value.trim(),idPhotoData:idPhoto,createdAt:Date.now(),createdBy:state.user.uid};const sale={saleId,customerId,customerName:customer.name,customerEmail:customer.email,customerNic:customer.nic,customerPhone:customer.phone,customerAddress:customer.address,projectId:project.id,projectName:project.name,blockId:block.id,blockNo:block.blockNo,perches:Number(block.perches||0),pricePerPerch:Number(block.pricePerPerch||0),saleType:$('#sType').value,totalPrice:total,paidTotal:paid,status:$('#sType').value==='SALE'?'SOLD':'RESERVED',paymentMethod:$('#sMethod').value,notes:$('#sNotes').value.trim(),customerSignatureData:customerSig,officerSignatureData:officerSig,officerId:state.user.uid,officerName:state.profile.name,createdAt:Date.now(),updatedAt:Date.now()};const payment=paid>0?{paymentId,saleId,customerId,customerName:customer.name,projectId:project.id,projectName:project.name,blockId:block.id,blockNo:block.blockNo,amount:paid,method:$('#sMethod').value,paymentDate:today(),receiptNo,createdAt:Date.now(),createdBy:state.user.uid}:null;
 const pdf=await generateSalePdf({...sale,documentNo:docNo,receiptNo});const pdfData=pdf.output('datauristring');if(approxBytes(pdfData)>800000)return toast('PDF is too large for a Firestore document. Reduce the ID photo size.');const documentData={documentNo:docNo,saleId,customerId,customerName:customer.name,customerEmail:customer.email,projectId:project.id,projectName:project.name,blockId:block.id,blockNo:block.blockNo,type:sale.saleType,pdfData,emailStatus:'SAVED',createdAt:Date.now(),createdBy:state.user.uid};
 try{const batch=writeBatch(db);batch.set(doc(db,C.customers,customerId),customer);batch.set(doc(db,C.sales,saleId),sale);batch.update(doc(db,C.blocks,block.id),{status:sale.status,currentSaleId:saleId,updatedAt:Date.now()});if(payment)batch.set(doc(db,C.payments,paymentId),payment);batch.set(doc(db,C.documents,docNo),documentData);await batch.commit();let emailStatus='SENDING';await updateDoc(doc(db,C.documents,docNo),{emailStatus:'SENDING'});try{await sendEmailWithPdf(documentData,sale,pdfData);emailStatus='SENT';await updateDoc(doc(db,C.documents,docNo),{emailStatus:'SENT',emailedAt:Date.now(),emailError:''})}catch(mailErr){emailStatus='FAILED';await updateDoc(doc(db,C.documents,docNo),{emailStatus:'FAILED',emailError:String(mailErr.message||mailErr)});audit('EMAIL_PDF_FAILED','document',docNo,{error:String(mailErr.message||mailErr),customerEmail:sale.customerEmail})}audit('CREATE_SALE','sale',saleId,{block:block.blockNo,total});pdf.save(`${docNo}.pdf`);closeModal();toast(emailStatus==='SENT'?'Sale saved. Signed PDF emailed to '+sale.customerEmail:'Sale saved, but PDF email failed. Open Documents and tap Retry Email.')}catch(err){toast('Sale failed: '+err.message)}})
}

function setupSignature(canvas){const dpr=Math.max(1,window.devicePixelRatio||1),rect=canvas.getBoundingClientRect();canvas.width=Math.floor(rect.width*dpr);canvas.height=Math.floor(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=2.2;ctx.strokeStyle='#111';let draw=false,last=null;const pt=e=>{const r=canvas.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:t.clientX-r.left,y:t.clientY-r.top}};const start=e=>{e.preventDefault();draw=true;last=pt(e)};const move=e=>{if(!draw)return;e.preventDefault();const p=pt(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;canvas.dataset.ink='1'};const end=()=>{draw=false;last=null};canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});return canvas}
function compressCanvas(canvas,maxW,maxH,q=.6){const out=document.createElement('canvas'),ratio=Math.min(maxW/canvas.width,maxH/canvas.height,1);out.width=Math.max(1,Math.round(canvas.width*ratio));out.height=Math.max(1,Math.round(canvas.height*ratio));const c=out.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,out.width,out.height);c.drawImage(canvas,0,0,out.width,out.height);return out.toDataURL('image/jpeg',q)}
function compressImage(file,maxDim=900,quality=.55){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{let w=img.width,h=img.height;const r=Math.min(maxDim/w,maxDim/h,1);w=Math.round(w*r);h=Math.round(h*r);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);let data=c.toDataURL('image/jpeg',quality);if(approxBytes(data)>700000){data=c.toDataURL('image/jpeg',.35)}res(data)};img.onerror=rej;img.src=fr.result};fr.onerror=rej;fr.readAsDataURL(file)})}
function approxBytes(dataUrl){return Math.ceil((String(dataUrl).length-(String(dataUrl).indexOf(',')+1))*3/4)}

async function generateSalePdf(s){const {jsPDF}=window.jspdf;const pdf=new jsPDF({unit:'mm',format:'a4'});const gold=[212,175,55],black=[10,10,10];pdf.setFillColor(...black);pdf.rect(0,0,210,33,'F');pdf.setTextColor(...gold);pdf.setFont('helvetica','bold');pdf.setFontSize(17);pdf.text('HERITAGE ASIA HOLDINGS (PVT) LTD',14,14);pdf.setFontSize(8);pdf.text(s.saleType==='SALE'?'LAND SALE CONFIRMATION':'LAND RESERVATION CONFIRMATION',14,21);pdf.setTextColor(90);pdf.setFont('helvetica','normal');pdf.text(`Document No: ${s.documentNo}`,14,40);pdf.text(`Date: ${new Date(s.createdAt).toLocaleDateString('en-GB')}`,145,40);pdf.setDrawColor(...gold);pdf.line(14,44,196,44);pdf.setTextColor(20);pdf.setFont('helvetica','bold');pdf.setFontSize(11);pdf.text('Customer Details',14,53);pdf.setFont('helvetica','normal');pdf.setFontSize(9);let y=60;[['Name',s.customerName],['NIC / Passport',s.customerNic],['Phone',s.customerPhone],['Email',s.customerEmail],['Address',s.customerAddress]].forEach(([a,b])=>{pdf.setFont('helvetica','bold');pdf.text(a+':',14,y);pdf.setFont('helvetica','normal');pdf.text(String(b||'-').slice(0,85),48,y);y+=7});pdf.setFont('helvetica','bold');pdf.setFontSize(11);pdf.text('Land / Transaction Details',14,y+3);y+=11;const rows=[['Project',s.projectName],['Block',s.blockNo],['Extent',`${Number(s.perches||0).toLocaleString('en-LK')} perches`],['Price / Perch',money(s.pricePerPerch||0)],['Transaction',s.saleType],['Total Price',money(s.totalPrice)],['Paid Now / Total Paid',money(s.paidTotal)],['Outstanding Balance',money(Math.max(0,s.totalPrice-s.paidTotal))],['Payment Method',s.paymentMethod],['Receipt No',s.receiptNo||'-'],['Sales / Site Officer',s.officerName]];pdf.setFontSize(9);rows.forEach(([a,b])=>{pdf.setFont('helvetica','bold');pdf.text(a+':',14,y);pdf.setFont('helvetica','normal');pdf.text(String(b||'-'),62,y);y+=7});if(s.notes){pdf.setFont('helvetica','bold');pdf.text('Notes / Terms:',14,y+2);pdf.setFont('helvetica','normal');const lines=pdf.splitTextToSize(s.notes,180);pdf.text(lines,14,y+8);y+=Math.max(15,lines.length*5+10)}y=Math.max(y+8,185);pdf.setDrawColor(170);pdf.rect(14,y,82,35);pdf.rect(114,y,82,35);if(s.customerSignatureData)pdf.addImage(s.customerSignatureData,'JPEG',19,y+4,72,21);if(s.officerSignatureData)pdf.addImage(s.officerSignatureData,'JPEG',119,y+4,72,21);pdf.setFont('helvetica','bold');pdf.setFontSize(8);pdf.text('CUSTOMER SIGNATURE',34,y+30);pdf.text('SALES / SITE OFFICER SIGNATURE',126,y+30);pdf.setFont('helvetica','normal');pdf.setTextColor(90);pdf.setFontSize(7);pdf.text('This system-generated document records the transaction details and signatures captured at the time of confirmation.',14,278,{maxWidth:182});return pdf}

async function sendEmailWithPdf(docData,sale,pdfData){const cfg=state.settings;if(!cfg.emailServiceId||!cfg.emailTemplateId||!cfg.emailPublicKey)throw new Error('EmailJS not configured');const resp=await fetch('https://api.emailjs.com/api/v1.0/email/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({service_id:cfg.emailServiceId,template_id:cfg.emailTemplateId,user_id:cfg.emailPublicKey,template_params:{to_email:sale.customerEmail,customer_name:sale.customerName,document_no:docData.documentNo,project_name:sale.projectName,block_no:sale.blockNo,transaction_type:sale.saleType,total_price:money(sale.totalPrice),paid_total:money(sale.paidTotal),balance:money(Math.max(0,sale.totalPrice-sale.paidTotal)),company_name:cfg.companyName,company_email:cfg.companyEmail,pdf_attachment:pdfData,pdf_filename:`${docData.documentNo}.pdf`}})});if(!resp.ok)throw new Error(await resp.text());return true}

window.openSale=sid=>{const s=state.sales.find(x=>x.id===sid||x.saleId===sid);if(!s)return;modal(`${modalHead(`${s.saleType}: ${esc(s.customerName)}`,`${esc(s.projectName)} — Block ${esc(s.blockNo)}`)}<div class="grid md:grid-cols-3 gap-3 mt-5"><div class="stat-card"><small>Total</small><strong class="accent">${money(s.totalPrice)}</strong></div><div class="stat-card"><small>Paid</small><strong>${money(s.paidTotal)}</strong></div><div class="stat-card"><small>Balance</small><strong>${money(Math.max(0,s.totalPrice-s.paidTotal))}</strong></div></div><div class="panel mt-4"><p class="text-sm"><b>NIC:</b> ${esc(s.customerNic)} &nbsp; <b>Phone:</b> ${esc(s.customerPhone)} &nbsp; <b>Email:</b> ${esc(s.customerEmail)}</p></div>${isFinance()&&s.totalPrice>s.paidTotal?`<button class="btn btn-gold mt-4" onclick="window.paymentModal('${s.saleId||s.id}')"><i data-lucide="wallet"></i>Record Installment</button>`:''}`)};
window.paymentModal=sid=>{const s=state.sales.find(x=>x.saleId===sid||x.id===sid);if(!s)return;const balance=Math.max(0,s.totalPrice-s.paidTotal);modal(`${modalHead('Record Installment',`${esc(s.customerName)} — ${esc(s.projectName)} / Block ${esc(s.blockNo)}`)}<form id="payForm" class="grid md:grid-cols-2 gap-4 mt-5"><label class="field"><span>Amount</span><input id="payAmount" type="number" min="1" max="${balance}" value="${balance}" required></label><label class="field"><span>Method</span><select id="payMethod"><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Cheque</option><option>Online</option></select></label><label class="field"><span>Date</span><input id="payDate" type="date" value="${today()}"></label><label class="field"><span>Reference</span><input id="payRef"></label><div class="md:col-span-2"><button class="btn btn-gold">Save Payment</button></div></form>`);$('#payForm').addEventListener('submit',async e=>{e.preventDefault();if(!isFinance())return toast('No finance permission');const amt=Number($('#payAmount').value||0);if(amt<=0||amt>balance)return toast('Invalid amount');const payId=id('pay'),receipt=`HAH-RC-${String(Date.now()).slice(-8)}`;await setDoc(doc(db,C.payments,payId),{paymentId:payId,saleId:s.saleId||s.id,customerId:s.customerId,customerName:s.customerName,projectId:s.projectId,projectName:s.projectName,blockId:s.blockId,blockNo:s.blockNo,amount:amt,method:$('#payMethod').value,paymentDate:$('#payDate').value,reference:$('#payRef').value.trim(),receiptNo:receipt,createdAt:Date.now(),createdBy:state.user.uid});await updateDoc(doc(db,C.sales,s.saleId||s.id),{paidTotal:Number(s.paidTotal||0)+amt,updatedAt:Date.now()});audit('RECORD_PAYMENT','sale',s.saleId||s.id,{amount:amt});closeModal();toast('Installment recorded')})}

window.downloadDoc=did=>{const d=state.documents.find(x=>x.id===did||x.documentNo===did);if(!d?.pdfData)return toast('PDF data not found');const a=document.createElement('a');a.href=d.pdfData;a.download=`${d.documentNo}.pdf`;document.body.appendChild(a);a.click();a.remove()};

window.resendDocEmail=async did=>{const d=state.documents.find(x=>x.id===did||x.documentNo===did);if(!d?.pdfData)return toast('PDF data not found');if(!d.customerEmail)return toast('Customer email not found');if(!state.settings.emailServiceId||!state.settings.emailTemplateId||!state.settings.emailPublicKey)return toast('Admin must configure EmailJS in Settings first');const sale=state.sales.find(x=>x.saleId===d.saleId||x.id===d.saleId)||{customerEmail:d.customerEmail,customerName:d.customerName,projectName:d.projectName,blockNo:d.blockNo,saleType:d.type,totalPrice:0,paidTotal:0};try{await updateDoc(doc(db,C.documents,d.documentNo||d.id),{emailStatus:'SENDING',emailError:''});await sendEmailWithPdf(d,sale,d.pdfData);await updateDoc(doc(db,C.documents,d.documentNo||d.id),{emailStatus:'SENT',emailedAt:Date.now(),emailError:''});audit('RESEND_DOCUMENT_EMAIL','document',d.documentNo||d.id,{customerEmail:d.customerEmail});toast('PDF emailed to '+d.customerEmail)}catch(err){await updateDoc(doc(db,C.documents,d.documentNo||d.id),{emailStatus:'FAILED',emailError:String(err.message||err)}).catch(()=>{});toast('Email failed: '+String(err.message||err))}};

$('#newUserBtn').addEventListener('click',()=>{if(!isAdmin())return;modal(`${modalHead('Create Management User','Creates Firebase Auth account and Firestore role profile.')}<form id="userForm" class="grid md:grid-cols-2 gap-4 mt-5"><label class="field"><span>Name</span><input id="uName" required></label><label class="field"><span>Email</span><input id="uEmail" type="email" required></label><label class="field"><span>Password</span><input id="uPassword" type="password" minlength="6" required></label><label class="field"><span>Role</span><select id="uRole"><option value="director">Director</option><option value="manager">Manager</option><option value="site_officer">Site Officer</option><option value="sales_officer">Sales Officer</option><option value="accountant">Accountant</option></select></label><div class="md:col-span-2"><button class="btn btn-gold">Create User</button></div></form>`);$('#userForm').addEventListener('submit',async e=>{e.preventDefault();let secondary=null;try{const app2=initializeApp(firebaseConfig,'secondary-'+Date.now());secondary=getAuth(app2);const cred=await createUserWithEmailAndPassword(secondary,$('#uEmail').value.trim(),$('#uPassword').value);await setDoc(doc(db,C.users,cred.user.uid),{uid:cred.user.uid,name:$('#uName').value.trim(),email:$('#uEmail').value.trim(),role:$('#uRole').value,active:true,createdAt:Date.now(),updatedAt:Date.now()});audit('CREATE_USER','user',cred.user.uid,{role:$('#uRole').value});await signOut(secondary);await deleteApp(app2);closeModal();toast('User created')}catch(err){toast('Create user failed: '+err.message)}})});

$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();if(!isAdmin())return toast('Admin only');const data={companyName:$('#setCompanyName').value.trim(),companyEmail:$('#setCompanyEmail').value.trim(),emailServiceId:$('#setEmailService').value.trim(),emailTemplateId:$('#setEmailTemplate').value.trim(),emailPublicKey:$('#setEmailPublicKey').value.trim(),updatedAt:Date.now()};await setDoc(doc(db,C.settings,'company'),data,{merge:true});state.settings={...state.settings,...data};audit('UPDATE_SETTINGS','settings','company');toast('Settings saved')});

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
lucide.createIcons();
